import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="grid grid-cols-5">
          <div className="w-full h-screen border-r-1 border-slate-100 sticky top-0">
            <nav className="w-full max-md:w-full max-md:ml-0">
              <div className="flex grow items-stretch gap-3 text-lg text-[rgba(186,186,186,1)] font-medium">
                <div className="bg-white w-full overflow-hidden mt-[5px] pl-2 space-y-4">
                  <div className=" py-8  w-full"></div>
                  <Link
                    href={"/"}
                    className="flex w-full items-center gap-[18px] overflow-hidden whitespace-nowrap px-6 py-3  hover:bg-gray-50 hover:text-black hover:cursor-pointer transition-colors rounded-md"
                  >
                    <img
                      src={
                        "https://api.builder.io/api/v1/image/assets/TEMP/8370f074bd03c4710006f2bf2e003011aa92985c?placeholderIfAbsent=true"
                      }
                      className="aspect-[1] object-contain w-[30px] self-stretch shrink-0 my-auto"
                      alt={""}
                    />
                    <div className="self-stretch my-auto text-lg">
                      Dashboard
                    </div>
                  </Link>
                  <Link
                    href={"/my-class"}
                    className="flex w-full items-center gap-[18px] overflow-hidden whitespace-nowrap px-6 py-3  hover:bg-gray-50 hover:text-black hover:cursor-pointer transition-colors rounded-md"
                  >
                    <img
                      src={
                        "https://api.builder.io/api/v1/image/assets/TEMP/f30331b34e2f521e939f97d2fd60930437fcf09f?placeholderIfAbsent=true"
                      }
                      className="aspect-[1] object-contain w-[30px] self-stretch shrink-0 my-auto"
                      alt={""}
                    />
                    <div className="self-stretch my-auto text-lg">
                      Kelas Saya
                    </div>
                  </Link>
                  <Link
                    href={"/browse-class"}
                    className="flex w-full items-center gap-[18px] overflow-hidden whitespace-nowrap px-6 py-3  hover:bg-gray-50 hover:text-black hover:cursor-pointer transition-colors rounded-md"
                  >
                    <img
                      src={
                        "https://api.builder.io/api/v1/image/assets/TEMP/6d81f51e56983843d1a02056035be33cf05f8c22?placeholderIfAbsent=true"
                      }
                      className="aspect-[1] object-contain w-[30px] self-stretch shrink-0 my-auto"
                      alt={""}
                    />
                    <div className="self-stretch my-auto text-lg">
                      Cari Kelas
                    </div>
                  </Link>
                  <Link
                    href={"/certification"}
                    className="flex w-full items-center gap-[18px] overflow-hidden whitespace-nowrap px-6 py-3  hover:bg-gray-50 hover:text-black hover:cursor-pointer transition-colors rounded-md"
                  >
                    <img
                      src={
                        "https://api.builder.io/api/v1/image/assets/TEMP/fc7273fca74b0d9a8ace7594ef8473a0297ba366?placeholderIfAbsent=true"
                      }
                      className="aspect-[1] object-contain w-[30px] self-stretch shrink-0 my-auto"
                      alt={""}
                    />
                    <div className="self-stretch my-auto text-lg">
                      Sertifikasi
                    </div>
                  </Link>
                  <Link
                    href={"/membership"}
                    className="flex w-full items-center gap-[18px] overflow-hidden whitespace-nowrap px-6 py-3  hover:bg-gray-50 hover:text-black hover:cursor-pointer transition-colors rounded-md"
                  >
                    <img
                      src={
                        "https://api.builder.io/api/v1/image/assets/TEMP/88034362f9da3bb38dd1bd04a3d3c457bdd4e1d4?placeholderIfAbsent=true"
                      }
                      className="aspect-[1] object-contain w-[30px] self-stretch shrink-0 my-auto"
                      alt={""}
                    />
                    <div className="self-stretch my-auto text-lg">
                      Keanggotaan
                    </div>
                  </Link>
                  <Link
                    href={"/payment"}
                    className="flex w-full items-center gap-[18px] overflow-hidden whitespace-nowrap px-6 py-3  hover:bg-gray-50 hover:text-black hover:cursor-pointer transition-colors rounded-md"
                  >
                    <img
                      src={
                        "https://api.builder.io/api/v1/image/assets/TEMP/470e8fe54016c2c5d358f42e59453b9776b2fc89?placeholderIfAbsent=true"
                      }
                      className="aspect-[1] object-contain w-[30px] self-stretch shrink-0 my-auto"
                      alt={""}
                    />
                    <div className="self-stretch my-auto text-lg">
                      Pembayaran
                    </div>
                  </Link>
                  <Link
                    href={"/setting"}
                    className="flex w-full items-center gap-[18px] overflow-hidden whitespace-nowrap px-6 py-3  hover:bg-gray-50 hover:text-black hover:cursor-pointer transition-colors rounded-md"
                  >
                    <img
                      src={
                        "https://api.builder.io/api/v1/image/assets/TEMP/5bb298cba5e76159c689ee1ee677479e6d1269e2?placeholderIfAbsent=true"
                      }
                      className="aspect-[1] object-contain w-[30px] self-stretch shrink-0 my-auto"
                      alt={""}
                    />
                    <div className="self-stretch my-auto text-lg">
                      Pengaturan
                    </div>
                  </Link>
                </div>
                <div className="bg-[rgba(238,238,238,1)] flex w-px shrink-0 h-[767px]"></div>
              </div>
            </nav>
          </div>
          <div className="col-span-4">
            <div className="bg-white w-full h-16 border-b-1 bg border-slate-50 sticky top-0">
              <div className="bg-[rgba(253,253,253,1)] flex justify-end items-center gap-[17px] text-lg text-[rgba(51,51,51,1)] font-bold flex-wrap grow shrink basis-auto pl-20">
                <div className="space-x-4">
                  <button className="hover:opacity-80 transition-opacity">
                    <img
                      src="https://api.builder.io/api/v1/image/assets/TEMP/16bc1f79067044f626c2de2ddb06af5077ec17bc?placeholderIfAbsent=true"
                      className="aspect-[1] object-contain w-[32px] self-stretch shrink-0 my-auto rounded-[50px]"
                      alt="Notification"
                    />
                  </button>
                  <button className="hover:opacity-80 transition-opacity">
                    <img
                      src="https://api.builder.io/api/v1/image/assets/TEMP/8a03b43d0ed7e325f28c4226717eb94a49ed2682?placeholderIfAbsent=true"
                      className="aspect-[1] object-contain w-[32px] self-stretch shrink-0 my-auto rounded-[50px]"
                      alt="Messages"
                    />
                  </button>
                </div>
                <div className="bg-[rgba(249,249,249,1)] self-stretch flex items-stretch gap-[40px_100px] px-[30px] py-4 max-md:px-5">
                  <div className="flex items-stretch gap-[17px]">
                    <img
                      src="https://api.builder.io/api/v1/image/assets/TEMP/835fd69a752d2769b64c8afb2e2638aa8b6e90eb?placeholderIfAbsent=true"
                      className="aspect-[1] object-contain w-9 shrink-0 rounded-[50%]"
                      alt="Profile"
                    />
                    <div className="basis-auto my-auto text-sm font-medium">
                      <h4>Fikri M</h4>
                    </div>
                  </div>
                  <button className="hover:opacity-80 transition-opacity">
                    <img
                      src="https://api.builder.io/api/v1/image/assets/TEMP/ea283bb0b874f7ce9e43e260d2e8146c6a71ca35?placeholderIfAbsent=true"
                      className="aspect-[1] object-contain w-5 shrink-0 my-auto"
                      alt="Dropdown"
                    />
                  </button>
                </div>
              </div>
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
